### ISSUE TITLE
Add Base templates

### ISSUE THREAD

**Issue by Samy-33** [3Peers/FusionIIIT#11]
@3Peers/uiteam push your respective work for base templates, as soon as possible.

**Comment by ghost** [comment]
Kanishka munshi has not changed the backend logic according to your logic.I
cannot push until he changes the logic.

**Comment by Samy-33** [comment]
@kmunshi97 , tell me about the progress and also one of your team members has not joined the team.

**Comment by Samy-33** [comment]
@3Peers/uiteam I have added the urls.py for each application. I don't have information about the internal components of each module and hence can't add the routes for the same. Please push your code, after resolving the likely differences between your codes.

**Comment by Samy-33** [comment]
@3Peers/uiteam , I have still not got the PR. I want it ASAP.

**Comment by kmunshi97** [comment]
Done

**Comment by narolkr** [comment]
@mayanksaurabh please push our templates too!

**Comment by kmunshi97** [comment]
Those modules which are not uploaded today will be pushed soon. Have patience!

**Comment by Samy-33** [comment]
@mayanksaurabh @kmunshi97 , the templates directory is messed up. I request you to clean it up. We have redundant base files, one in fusion and one in dashboard. I suggest you two to communicate properly, confirm the changes and then push.  
@pranjulps3 please do not merge any PR.

**Comment by Samy-33** [comment]
@ravuri0898 Please add your templates, ASAP.
