### ISSUE TITLE
Help needed in using mysql as dbms

### ISSUE THREAD

**Issue by Samy-33** [3Peers/FusionIIIT#14]
@3Peers/databaseteam 
Please ensure that nobody faces errors while using sql as database.
@gautamyadavs @varnu02 Please attach screenshots of error if possible.

**Comment by varnika98** [comment]
Screenshot of the error.
![screenshot 23](https://user-images.githubusercontent.com/24393318/31314515-a8f15488-abb7-11e7-83dc-e56dc94a1656.png)

**Comment by gautamyadavs** [comment]
![untitled](https://user-images.githubusercontent.com/25340998/31314520-94288a58-ac20-11e7-87a7-3d68d57317c6.png)
Even after installing both neither of them is working

**Comment by Samy-33** [comment]
@gautamyadavs   
For **mac/linux** , check the following  
  * You have mysql installed : `$ which mysql`  
  * If not then install **mysql** using : `$ sudo apt install mysql-server` or `$ yum install mysql-server`  
  * Then install **libmysqlclient-dev** : `$ sudo apt install libmysqlclient-dev` or `$ yum install libmysqlclient-dev`  
  * After that in your virtualenv install **mysqlclient** : `$ pip install mysqlclient`  

@varnu02 , I will get back to you for windows as soon as I get it resolved.  
Please comment if the issue gets resolved.

**Comment by arshadsid** [comment]
@varnu02 update pip, setuptools. Install mysqlclient and mysql-python

**Comment by arshadsid** [comment]
Create a database named fusion before you apply migrations

**Comment by gautamyadavs** [comment]
I'm posting this because I can't find a solution anywhere so I have to do it on my own.
For Mac:
first download Xcode from App Store and MySqlWorkbench from https://dev.mysql.com/downloads/workbench/

Run the following commands in terminal,
-  $ brew install mysql
-  $ export PATH=$PATH:/Applications/MySQLWorkbench.app/Contents/MacOS
-  $ xcode-select --install
-  $ pip install mysqlclient

**Comment by arshadsid** [comment]
Others who still have problems please attend the meeting

**Comment by Samy-33** [comment]
@arshadsid, have all problems related to mysql db been resolved?

**Comment by arshadsid** [comment]
No the error for visual Studio 14 fails with exit status 2.
Trying to solve.

**Comment by pranjulps3** [comment]
For **Windows**:

- Download mysql installer community via the [link](https://dev.mysql.com/downloads/installer/). Install mysql server and mysql connector C++(optional) and configure the server root credentials.

- Open command window and goto `C:\Program Files\MySQL\MySQL Server 5.7\bin` and create your database for fusion.
```
cd C:\Program Files\MySQL\MySQL Server 5.7\bin
mysql -u root -p
```
After this mysql will ask for the password used for root while configuring your server. Enter the password and create a database named 'fusion' by
`CREATE DATABASE fusion;`

- Now go to settings.py in Fusion and edit the database settings accordingly.
```
DATABASES = {
   'default':
        {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'fusion',
            'USER': 'root',
            'PASSWORD': '<your password>',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        },
}
```

- Finally install mysqlclient by `pip install mysqlclient`

Now the server should run without any errors.

**Comment by Samy-33** [comment]
And everyone, add the `settings.py` file in `.gitignore` so that it doesn't change the stable master `settings.py`.

**Comment by Samy-33** [comment]
Nobody is facing any more errors. Thank you @arshadsid, @gautamyadavs and @pranjulps3
