### ISSUE TITLE
Runserver Issues

### ISSUE THREAD

**Issue by kmunshi97** [3Peers/FusionIIIT#42]
Please have a look at these warnings!

![screenshot from 2017-10-17 00-42-51](https://user-images.githubusercontent.com/25405970/31630701-072048ba-b2d5-11e7-80f4-25559d520195.png)

**Comment by Samy-33** [comment]
@3Peers/academic-procedures-management and @3Peers/visitor-hostel-management, have a look at these warnings while running the server,

**Comment by anuj97** [comment]
@kmunshi97 @Samy-33 no need to worry, you can go ahead, there's nothing that needs to be resolved

**Comment by pranjulps3** [comment]
@3Peers/visitor-hostel-management correct the warnings and send a PR ASAP.
