### ISSUE TITLE
Runserver Issues

### ISSUE THREAD

**Issue by anuj97** [3Peers/FusionIIIT#68]
![screenshot from 2017-10-28 12-21-21](https://user-images.githubusercontent.com/18463482/32132168-25e855fc-bbdc-11e7-80fb-caec6aa86c3c.png)

Anybody facing this?

**Comment by kmunshi97** [comment]
These are placement module issues.

**Comment by Samy-33** [comment]
@3Peers/placement-management-system , this xhtml2pdf package you are using is not compatible with python3, it is written in python2. Please resplve this.

**Comment by gautamyadavs** [comment]
For python 3 you have to write,
pip install --pre xhtml2pdf
I wrote it in requirements.txt but idk why it didn't get merged when u accepted the pull request

**Comment by Samy-33** [comment]
Add this to README and post the reference here.

**Comment by arshadsid** [comment]
@anuj97 @kmunshi97 @Samy-33  
I have added the required packages in requirements.txt.
Install requirements file again to remove the above said error.
#71

**Comment by Samy-33** [comment]
If this issue is resolved, please close it.
