### ISSUE TITLE
Runserver Issues

### ISSUE THREAD

**Issue by anuj97** [3Peers/FusionIIIT#78]
![screenshot from 2017-11-04 13-08-35](https://user-images.githubusercontent.com/18463482/32403499-6ff2f8c0-c161-11e7-9372-ec31f8f06ba4.png)

@Samy-33 @pranjulps3

**Comment by pranjulps3** [comment]
@3Peers/health-care-management  please look into this ASAP.

**Comment by Samy-33** [comment]
@anuj97 Is this resolved?

**Comment by anuj97** [comment]
no, not yet

**Comment by prajjwalsinghzz14** [comment]
This is just a repetition of `url(r'^healthcenter/', include('applications.health_center.urls')),` under 
```
urlpatterns = [
.....
]
```
inside `FusionIIIT/Fusion/urls.py`
Removing one of the two same lines will remove the error.
