### ISSUE TITLE
Front-End Problems

### ISSUE THREAD

**Issue by anuj97** [3Peers/FusionIIIT#81]
![screenshot from 2017-11-05 07-03-59](https://user-images.githubusercontent.com/18463482/32411074-b5c3134e-c1f7-11e7-92aa-d557d6d273c5.png)

@kmunshi97 @Samy-33 @pranjulps3 
@varnu02 AFAIK you've been facing the same problem

**Comment by kmunshi97** [comment]
I can assure you I have personally checked the screens before sending the pull requests. 
And I can say there is huge chance that it is because of extra/less div tags.

**Comment by Samy-33** [comment]
@3Peers/visitor-hostel-management @kmunshi97 , set up a meeting and get this thing resolved.
