### ISSUE TITLE
Explain this in global models.

### ISSUE THREAD

**Issue by Samy-33** [3Peers/FusionIIIT#88]
https://github.com/3Peers/FusionIIIT/blob/cb226b9c28f3d9ea28c18738c616c9691d1c5ced/FusionIIIT/applications/globals/models.py#L39

@arshadsid What is the use of this `CharField` as `primary_key`?

**Comment by arshadsid** [comment]
@Samy-33 that is roll number for students and pf number for faculty, some students on research have roll numbers in the format NITKxxxxxx. Keeping that in mind, it was kept char.

**Comment by Samy-33** [comment]
Understood, thanks.
